import google.generativeai as genai
from PIL import Image, ImageDraw, ImageFont
import os
import sys

# --- Configuration ---
# IMPORTANT: It's best practice to set your API key as an environment variable
# rather than hardcoding it directly in the script.
#
# To set it in your terminal (for the current session):
# For Linux/macOS: export GOOGLE_API_KEY='YOUR_API_KEY'
# For Windows (CMD): set GOOGLE_API_KEY=YOUR_API_KEY
# For Windows (PowerShell): $env:GOOGLE_API_KEY="YOUR_API_KEY"
#
# If you must hardcode it for a quick test, uncomment the following line:
# os.environ['GOOGLE_API_KEY'] = "YOUR_API_KEY_HERE"

try:
    # Configure the generative AI library with your API key
    genai.configure(api_key=os.environ["GEMINI_API_KEY"])
except KeyError:
    print("--------------------------------------------------")
    print("ERROR: GOOGLE_API_KEY environment variable not set.")
    print("Please set the variable and run the script again.")
    print("--------------------------------------------------")
    sys.exit(1) # Exit the script if the key is not found


def generate_image_code(user_prompt: str) -> str:
    """
    Sends a prompt to the Gemini model to generate Python code for creating an image.
    
    Args:
        user_prompt: The user's description of the image.

    Returns:
        The Python code generated by the LLM as a string, or None if an error occurs.
    """
    
    # --- This is the "master prompt" that instructs the LLM ---
    # It provides context, rules, and the user's specific request.
    # This detailed instruction helps in getting a reliable and safe output.
    master_prompt = f"""
    You are a helpful AI assistant that generates Python code to create images using the Pillow library.
    Your task is to generate a complete, executable Python script based on the user's request.

    **Instructions & Rules:**
    1.  The generated code must be a complete Python script.
    2.  It MUST use the `Pillow` (PIL) library.
    3.  The script must save the final image to a file named 'generated_image.png'.
    4.  Do NOT include any code for displaying the image (e.g., `image.show()`), only save it.
    5.  Image save directory is 'assets/'
    6.  The image dimensions should be 512x512 pixels unless the user specifies otherwise.
    7.  Do not write any code that performs file system operations other than saving the single image file (e.g., no reading files, deleting files, or listing directories).
    8.  IMAGE BACKGROUND SHOULD BE TRANSPARENT.
    9.  Do not include any code that makes network requests.
    10. The generated code must be self-contained and not require any external assets.
    11. Assume that `Pillow` is already installed.
    12. Your entire response should be only the Python code, enclosed in ```python ... ```.

    **User's Image Request:**
    "{user_prompt}"

    Now, generate the Python code.
    """

    try:
        # Initialize the Gemini model
        model = genai.GenerativeModel('gemini-2.5-flash')
        
        # Send the prompt and get the response
        response = model.generate_content(master_prompt)
        
        # Clean up the response to extract only the Python code
        code = response.text.strip()
        if code.startswith("```python"):
            code = code[9:]
        if code.endswith("```"):
            code = code[:-3]
            
        return code.strip()

    except Exception as e:
        print(f"\nAn error occurred while communicating with the Gemini API: {e}")
        return None


def execute_generated_code(code: str):
    """
    Executes the Python code generated by the LLM.

    Args:
        code: A string containing the Python code to be executed.
    """
    print("\n--- Executing Generated Code ---")
    try:
        # The `exec()` function runs the string of Python code.
        # We provide it with a global context so it can import libraries.
        exec(code, globals())
        
        
        print("--- Code Executed Successfully ---")
        print("Image saved as 'generated_image.png'")
        
        # Try to open the image for the user
        try:
            img = Image.open('assets/generated_image.png')
            img.show()
        except Exception:
            print("You can now open 'generated_image.png' to see the result.")

    except Exception as e:
        print(f"\nAn error occurred while executing the generated code: {e}")
        print("\n--- Generated Code (for debugging) ---")
        print(code)
        print("--------------------------------------")


def main():
    """Main function to run the program."""
    print("--- Dynamic Image Generator using an LLM ---")
    print("Describe the image you want to create (or type 'quit' to exit).")
    print("Examples:")
    print(" - A yellow smiley face on a black background")
    print(" - A sky-blue background with a white cloud in the center")
    print(" - A simple house with a brown roof and a red door\n")

    while True:
        user_input = input("> ")
        if user_input.lower() == 'quit':
            break
        
        print(f"\nRequesting code for: '{user_input}'...")
        generated_code = generate_image_code(user_input)
        
        if generated_code:
            execute_generated_code(generated_code)
        else:
            print("Could not generate code. Please try again.")
        
        print("\n" + "="*40 + "\n")

if __name__ == "__main__":
    main()